//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FarmaciaEntities : DbContext
    {
        public FarmaciaEntities()
            : base("name=FarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual DbSet<PRESENTACION> PRESENTACIONs { get; set; }
        public virtual DbSet<TIPOESPECIFICO> TIPOESPECIFICOes { get; set; }
        public virtual DbSet<TIPOFARMACO> TIPOFARMACOes { get; set; }
        public virtual DbSet<TIPOMEDICAMENTO> TIPOMEDICAMENTOes { get; set; }
        public virtual DbSet<UNIDADMEDIDA> UNIDADMEDIDAs { get; set; }
        public virtual DbSet<TIPOSUSUARIO> TIPOSUSUARIOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
    
        public virtual ObjectResult<ObtenerTablaUsuariovalido_Result> ObtenerTablaUsuariovalido(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerTablaUsuariovalido_Result>("ObtenerTablaUsuariovalido", userParameter, passParameter);
        }
    }
}
