//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FarmaciaEntities1 : DbContext
    {
        public FarmaciaEntities1()
            : base("name=FarmaciaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTO { get; set; }
        public virtual DbSet<PRESENTACION> PRESENTACION { get; set; }
        public virtual DbSet<TIPOESPECIFICO> TIPOESPECIFICO { get; set; }
        public virtual DbSet<TIPOFARMACO> TIPOFARMACO { get; set; }
        public virtual DbSet<TIPOMEDICAMENTO> TIPOMEDICAMENTO { get; set; }
        public virtual DbSet<UNIDADMEDIDA> UNIDADMEDIDA { get; set; }
    
        public virtual int checkStocks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("checkStocks");
        }
    
        public virtual ObjectResult<ObtenerTablaUsuariovalido_Result> ObtenerTablaUsuariovalido(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerTablaUsuariovalido_Result>("ObtenerTablaUsuariovalido", userParameter, passParameter);
        }
    }
}
