//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENTO
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public int presentacion { get; set; }
        public int tipoMedicamento { get; set; }
        public int tipoEspecifico { get; set; }
        public int cantidad { get; set; }
        public string indicaciones { get; set; }
        public int tipoFarmaco { get; set; }
        public int existencia { get; set; }
    
        public virtual PRESENTACION PRESENTACION1 { get; set; }
        public virtual TIPOESPECIFICO TIPOESPECIFICO1 { get; set; }
        public virtual TIPOFARMACO TIPOFARMACO1 { get; set; }
        public virtual TIPOMEDICAMENTO TIPOMEDICAMENTO1 { get; set; }
    }
}
