//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOESPECIFICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOESPECIFICO()
        {
            this.TIPOMEDICAMENTOes = new HashSet<TIPOMEDICAMENTO>();
        }
    
        public int id { get; set; }
        public string nombreTipEsp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOMEDICAMENTO> TIPOMEDICAMENTOes { get; set; }
    }
}
