//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOMEDICAMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOMEDICAMENTO()
        {
            this.MEDICAMENTOes = new HashSet<MEDICAMENTO>();
        }
    
        public int id { get; set; }
        public string nombreTipo { get; set; }
        public int unidadMedida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENTO> MEDICAMENTOes { get; set; }
        public virtual UNIDADMEDIDA UNIDADMEDIDA1 { get; set; }
    }
}
