//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmciaApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int usuarioID { get; set; }
        public string primerNombre { get; set; }
        public string primerApellido { get; set; }
        public string nombreUsuario { get; set; }
        public string contraseña { get; set; }
        public short tipoUsuario { get; set; }
        public string email { get; set; }
    
        public virtual TIPOSUSUARIO TIPOSUSUARIO { get; set; }
    }
}
